### ISSUE TITLE
跟hexo官方推的那个加密博客插件冲突

### ISSUE THREAD

**Issue by huiwang** [huiwang/hexo-baidu-url-submit#9]
~/blog $ hexo g
INFO Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/trouble...
TypeError: Cannot read property 'count' of undefined
at Hexo.module.exports (/Users/blog/node_modules/hexo-baidu-url-submit/lib/generator.js:4:40)
at Hexo.tryCatcher (/Users/blog/node_modules/bluebird/js/release/util.js:16:23)
at Hexo.<anonymous> (/Users/blog/node_modules/bluebird/js/release/method.js:15:34)
at /Users//blog/node_modules/hexo/lib/hexo/index.js:340:24
at tryCatcher (/Users/blog/node_modules/bluebird/js/release/util.js:16:23)
at MappingPromiseArray._promiseFulfilled (/Users/blog/node_modules/bluebird/js/release/map.js:61:38)
at MappingPromiseArray.PromiseArray._iterate (/Users/blog/node_modules/bluebird/js/release/promise_array.js:113:31)
at MappingPromiseArray.init (/Users/blog/node_modules/bluebird/js/release/promise_array.js:77:10)
at MappingPromiseArray._asyncInit (/Users/blog/node_modules/bluebird/js/release/map.js:30:10)
at Async._drainQueue (/Users/blog/node_modules/bluebird/js/release/async.js:138:12)
at Async._drainQueues (/Users/blog/node_modules/bluebird/js/release/async.js:143:10)
at Immediate.Async.drainQueues (/Users/blog/node_modules/bluebird/js/release/async.js:17:14)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by tmcyfy** [comment]
不知道是不是在hexo博客加密的那个插件里生成的模版可能跟普通的post模版不一致所致。

**Comment by huiwang** [comment]
@tmcyfy 加密插件的连接能发一下吗，谢谢

**Comment by tmcyfy** [comment]
在官方页面上你们就在隔壁啊

hexo-blog-encrypt

链接：https://github.com/MikeCoder/hexo-blog-encrypt

**Comment by huiwang** [comment]
> Cannot read property 'count' of undefined
错误消息说的是count没有定义，不知道你是怎么看出来冲突的？
你能把你的config发来看一下吗？

**Comment by Nautilus-N** [comment]
你好，我也遇到了一样的报错信息，请问这个问题得到解决了吗？
